# Generated by Django 5.2.8 on 2026-10-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
